- project:
    check:
      jobs:
        - nuage-ospd-deployment-16-patch-localmirror-vrs
        - nuage-ospd-tempest-16-patch-localmirror-vrs
    gate:
      jobs:
        - nuage-ospd-deployment-16-patch-localmirror-vrs
        - nuage-ospd-tempest-16-patch-localmirror-vrs

- job:
    name: nuage-ospd-deployment-16-patch-localmirror-vrs
    branches: .*
    parent: ospd-deployment-16-patch-localmirror-vrs
    provides: nuage-ospd-deployment-16-patch-localmirror-vrs
    description: |
      Integrated gate job for OSPD 16 using a virtual undercloud and overcloud.
    nodeset: openstack-single-node-rhel7
    irrelevant-files: (.+\.rst)|(.+\.md)|(.+\.cfg)|(.+\.spec)|(.+setup\.py)|(.+LICENSE)|(.+PNG)|(.+png)|(.+JPEG)|(.+jpeg)

- job:
    name: nuage-ospd-tempest-16-patch-localmirror-vrs
    parent: ospd-tempest-16-patch-localmirror-vrs
    dependencies: nuage-ospd-deployment-16-patch-localmirror-vrs
    requires: nuage-ospd-deployment-16-patch-localmirror-vrs
    branches: .*
    irrelevant-files: (.+\.rst)|(.+\.md)|(.+\.cfg)|(.+\.spec)|(.+setup\.py)|(.+LICENSE)|(.+PNG)|(.+png)|(.+JPEG)|(.+jpeg)

