heat_template_version: rocky

description: >
  OpenStack Neutron ML2/Nuage plugin configured with Puppet

parameters:
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  # Config specific parameters, to be provided via parameter_defaults
  NeutronNuageNetPartitionName:
    description: Specifies the title that you will see on the VSD
    type: string
    default: 'default_name'

  NeutronNuageVSDIp:
    description: IP address and port of the Virtual Services Directory
    type: string

  NeutronNuageVSDUsername:
    description: Username to be used to log into VSD
    type: string

  NeutronNuageVSDPassword:
    description: Password to be used to log into VSD
    type: string

  NeutronNuageVSDOrganization:
    description: Organization parameter required to log into VSD
    type: string
    default: 'organization'

  NeutronNuageBaseURIVersion:
    description: URI version to be used based on the VSD release
    type: string
    default: 'default_uri_version'

  NeutronNuageCMSId:
    description: Cloud Management System ID (CMS ID) to distinguish between OS instances on the same VSD
    type: string

  UseForwardedFor:
    description: Treat X-Forwarded-For as the canonical remote address. Only enable this if you have a sanitizing proxy.
    type: boolean
    default: false

  NuageDefaultAllowNonIP:
    description: To allow non-IP traffic by default
    type: boolean
    default: false

  NuageGpgKeys:
    type: comma_delimited_list
    default: []
    description: Nuage GPG keys

resources:

  NeutronMl2Base:
    type: /usr/share/openstack-tripleo-heat-templates/deployment/neutron/neutron-plugin-ml2.yaml

    properties:
      ServiceData: {get_param: ServiceData}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}
      RoleName: {get_param: RoleName}
      RoleParameters: {get_param: RoleParameters}

outputs:
  role_data:
    description: Role data for the Neutron ML2/Nuage plugin
    value:
      service_name: neutron_plugin_ml2_nuage
      config_settings:
        map_merge:
          - get_attr: [NeutronMl2Base, role_data, config_settings]
          - neutron::plugins::ml2::nuage::nuage_net_partition_name: {get_param: NeutronNuageNetPartitionName}
            neutron::plugins::ml2::nuage::nuage_vsd_ip: {get_param: NeutronNuageVSDIp}
            neutron::plugins::ml2::nuage::nuage_vsd_username: {get_param: NeutronNuageVSDUsername}
            neutron::plugins::ml2::nuage::nuage_vsd_password: {get_param: NeutronNuageVSDPassword}
            neutron::plugins::ml2::nuage::nuage_vsd_organization: {get_param: NeutronNuageVSDOrganization}
            neutron::plugins::ml2::nuage::nuage_base_uri_version: {get_param: NeutronNuageBaseURIVersion}
            neutron::plugins::ml2::nuage::nuage_cms_id: {get_param: NeutronNuageCMSId}
            neutron::plugins::ml2::nuage::nuage_default_allow_non_ip: {get_param: NuageDefaultAllowNonIP}
            nova::api::use_forwarded_for: {get_param: UseForwardedFor}
      step_config: |
        include tripleo::profile::base::neutron::plugins::ml2
      metadata_settings:
        get_attr: [NeutronMl2Base, role_data, metadata_settings]
      deploy_steps_tasks:
        - when: step|int == 1
          block:
            - name: Check if Nuage is installed or not
              shell: rpm -q nuage-openstack-neutronclient selinux-policy-nuage
              register: nuage_check
              failed_when: false
            - name: Installing Nuage Packages and Dependencies
              block:
              # Only install when nuage is not installed already.
              - name: set nuage_gpg_keys fact
                set_fact:
                  nuage_gpg_keys: {get_param: NuageGpgKeys }
              - name: Adding nuage_gpg_keys on overcloud node
                rpm_key:
                  state: present
                  key: "{{ item }}"
                with_items:
                  - "{{ nuage_gpg_keys }}"
                when:
                  - nuage_gpg_keys != []
              - debug:
                  msg: "No NuageGpgKeys Environment variable is set for this deployment"
                when:
                  - nuage_gpg_keys == []
              - name: Install Nuage Neutron Client on overcloud controller node
                yum:
                  name: "{{ packages }}"
                  state: present
                vars:
                  packages:
                    - nuage-openstack-neutronclient
                    - selinux-policy-nuage
              when: nuage_check.rc != 0
