# OpenStack version number
version: 13
# Nuage Release and format is <Major-release, use '-' instead of '.'>-<Minor-release>-<Updated-release>
# for exmaple: Nuage release 5.4.1u4 please enter following
release: 5-4-1-u4
# Tag for Nuage container images
tag: latest
# Undercloud Local Registry IP Address:Port
local_registry: 192.168.24.1:8787
# List of Nuage containers
nuage_images: ['heat-api-cfn', 'heat-api', 'heat-engine', 'horizon', 'neutron-server' ,'nova-compute']
