parameter_defaults:
  NovaSchedulerDefaultFilters: "RetryFilter,AvailabilityZoneFilter,ComputeFilter,ComputeCapabilitiesFilter,ImagePropertiesFilter,ServerGroupAntiAffinityFilter,ServerGroupAffinityFilter,PciPassthroughFilter,NUMATopologyFilter,AggregateInstanceExtraSpecsFilter"
  NeutronFastpathOptVolumes:
    - /run/fp_rpcd:/run/fp_rpcd
  ComputeAvrsSingleParameters:
    KernelArgs: "default_hugepagesz=1G hugepagesz=1G hugepages=64 iommu=pt intel_iommu=on isolcpus=1-7"
    NovaComputeCpuSharedSet: [2-4]
    NovaComputeCpuDedicatedSet: [5-7]
    FastPathNics: "0000:06:00.1 0000:06:00.2"
    FastPathMask: "1"
    FastPathNicDescriptors: "--rx-cp-filter-mode=dedicated-queue --tx-cp-filter-mode=software-filter --cp-filter-virtual-ports=enable --cp-filter-cpu-budget=10 --nb-rxd=4096 --nb-txd=4096 --rx-cp-filter-threshold=75% --tx-cp-filter-threshold=75%"
    FastPathOptions: "--mod-opt=fp-vswitch:--flows=250000 --max-nfct=500000"
    FastPathOffload: "off"

  ComputeAvrsDualParameters:
    KernelArgs: "default_hugepagesz=1G hugepagesz=1G hugepages=64 iommu=pt intel_iommu=on isolcpus=1-7,9-15"
    NovaComputeCpuSharedSet: [2-7]
    NovaComputeCpuDedicatedSet: [10-15]
    FastPathNics: "0000:06:00.1 0000:06:00.2"
    FastPathMask: "1,9"
    FastPathNicDescriptors: "--rx-cp-filter-mode=dedicated-queue --tx-cp-filter-mode=software-filter --cp-filter-virtual-ports=enable --cp-filter-cpu-budget=10 --nb-rxd=4096 --nb-txd=4096 --rx-cp-filter-threshold=75% --tx-cp-filter-threshold=75%"
    FastPathOptions: "--mod-opt=fp-vswitch:--flows=250000 --max-nfct=500000"
    FastPathOffload: "off"

